name: build
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16, 18, 20 ]

    name: node v${{ matrix.node-version }} build

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
